<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="GM.Exceptions" Version="1.2.1" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
        <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Update="Resources\GMExceptionsResource.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
        <LastGenOutput>GM.Exceptions.Resource.Designer.cs</LastGenOutput>
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </EmbeddedResource>
    </ItemGroup>

    <ItemGroup>
      <Compile Update="Resources\GMExceptionsResource.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>GMExceptionsResource.resx</DependentUpon>
      </Compile>
    </ItemGroup>

</Project>
